version: "3.8"
services:
  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - net

  rabbitmq:
    image: rabbitmq:3.8.25-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - /rabbitmq/data/:/var/lib/rabbitmq/
      - /rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - net

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - rabbitmq
    networks:
      - net
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes:
      - ./uploads:/var/lib/uploads

volumes:
  data:

networks:
  net:
    driver: bridge
